### PR TITLE
Badge system overhaul + Retired Logi 

### LINKED ISSUE #135: Inactive L badge
- [ ] Add it as a tag that HQ-FC can give 
- [ ] Make it show on x up
- [ ] Add it to badges guide
- [ ] Unfuck acl so they aren't all linked or whatever
- [ ] Make it so that INACTIVE cannot be invited by trainee fc (might as well do the same with nestors without L badge at the same time)
- [ ] probably something else i'm missing rn

### PR DESCRIPTION
**Pull request by samuelgrant**
This PR resolves #135.

_**WARNING:** This update requires you to run migration 0003!_ 
* The MySQL migration will move all badges from the `admins` table to the `badge_assignment` table.  This migration is highly destructive, it is recommended that you back up the database before proceeding.

* The Sqlite migration only creates the new tables and seeds the badge table. You will need to migrate `badge_assignments` manually. 

---

This PR alters the way the waitlist handles specialist badges, the core changes are as follows: 
* Separated specialist badges (referred to as badges hereafter) from the ACL system
* Allows an FC to retain specialist badges when they are granted FC permissions. This means they will not need to be reassigned badges if they leave the FC team
* Created a new badges page where FCs can audit, assign and revoke badges
* Removed the badge settings from the ACL modal which is now restricted to trainers/council/admin, and added a new badges modal
* Added a Retired-Logi badge (defined in the migration)
* Added logic in the invite controller to stop Trainees from inviting retired logi and Training Nestors ([invite.rs#L69-L84](https://github.com/samuelgrant/tdf-waitlist/blob/79b0816875e2813b5d87bb865d12851081905da7/backend/src/routes/waitlist/invite.rs#L69-L84))

**Manage Badges**

Users with shell access to the database can create, delete or update badges within the `badge` table. 
<details>
   <summary>SQL Example: Creating a badge</summary>
 
   ```sql
   INSERT INTO badge (name) VALUES ('badge_name');
   ```
The badge name needs to match a KEY in the tagBadges object (see below) - otherwise, it will not render correctly
https://github.com/samuelgrant/tdf-waitlist/blob/79b0816875e2813b5d87bb865d12851081905da7/frontend/src/Components/Badge.js#L75-L87.

The badge order on the Xup card can be changed here: https://github.com/samuelgrant/tdf-waitlist/blob/79b0816875e2813b5d87bb865d12851081905da7/frontend/src/Pages/Waitlist/XCard.js#L29-L41
</details>

---
**Change Log**
* Database: 
   * Created table `badge` to manage tag options. These tags are used to dynamically populate UI elements on the badge page, and badge modals
   * Created table `badge_assignments` to track which badges have been assigned to a pilot, when and by whom 
   * Provided SQL scripts for MySQL to migrate badges from the `admins` table into `badge_assignments`

* Auth/Permissions
   * Removed the waitlist-tag scopes for badges
   * Removed the scopes that allow an FC to manage badges (e.g., `access-manage:l`) - The auth backend will be further developed in a later PR and legacy code will be removed
   * Created a new scope `badges-manage` used to access the badge page/modal and assigned it to HQ-FCs
   * Restricted the ACL modal to Trainers, Council and Admins
 
* Controllers
   * Created a new routes file for badges
   * Added GET/POST/DELETE endpoints to manage badges
   * Updated the pilot info endpoint to include information about a pilot's badges
  
* UI/UX
   * Created a badges page where badges can be assigned, revoked and audited
   * Removed the filters from ACL page - ACL management will be further improved in a future PR
   * Added a new NPM package `react-data-table-component` so e can render data tables on admin pages
   * Added the retired logi badge to the badge guide

* Fleet
  *  Created a Retired Logi badge that can be assigned by HQ-FCs,
  *  Blocked trainees/advanced trainees from inviting retired logi and training nestors

### CODE REVIEW

**Comment by testkil** [comment]
badges.rs is fucked

does not compile.

**Comment by samuelgrant** [comment]
Thanks for the heads up.

Compiling fine on my end, it could be a difference in our dev environment? I'm running Ubuntu.

Will fix this issue tomorrow.

**Comment by samuelgrant** [comment]
> badges.rs is fucked
> 
> does not compile

I can't repo these errors natively within my dev machine (Ubuntu, WSL2). I have been able to partially reproduce them within docker and I think I've fixed them, will commit the changes in a moment. However, I am unable to test the fix on my end due to some technical issues with Docker. 

If you could pull the updated code, and attempt to build the app that would be fantastic.

---
**Changes:**
• Fixed five property capitalization issues in lines 128, 130-131 & 136-137
• Used the more traditional `format!()` method rather than the string interpolation method as this is unsupported by older versions of Rust.

**Comment by samuelgrant** [comment]
Okay, this PR should be ready for review @luna-duclos.

If you have been following along with the changes on your dev machine you will need to drop the badge and badge assignments table and re-run the relevant migrations as I have added a new column. I have checked all of the features that have been implemented to make sure they work as I would expect, but please take a good look as well before you merge.

Alex has brought a few UI concerns to me, after consideration and discussions with others I have opted not to implement his requests, my rationale is below: 

- Replace the badge filter select input with buttons. 
   - When working with data tables a `<select>` element would be the typical component. 
   - The new system can have as many badges as desired, this could get out of hand if there was a button for every filter. A select element provides a much cleaner UI element that scales nicely

- Tie the Logi and Retired-Logi options into one filter 
   - The system is dynamic, I am purposely trying to avoid hard-coding things so we can easily add/remove badges with as few code changes as possible. For this reason, the filters are dynamic, therefore the filters **have to** be separate

- The order of badges on the badge modal isn't Alex's preferred order
   - Again dynamic system. It could be possible to sort alphabetically or to add a sort_index integer in the badge table.  PRs on both these options would be easy in the future should it become necessary

- One row per character per badge is too bloated. On the badges page show one row per character and create a history page to show who assigned what and when
   - Talked about this with other FCs who felt it was fine. Filters can mitigate the bloat concern

- Data table design on the badges page is different to other admin pages (ACL/Bans)
   - I would like to update these pages over time to improve usability. They could be standardised at that time.

**Pull request merged**
